repository: Return EOWNER when repository permission validation fails
Should prevent libgit claiming that repository does not exist when it
does.

:~> git ls-remote /srv/git/kernel-source.git | head -n3
41037b9c54949ab7df9d32e8bc753c059b27c66c        HEAD
7a68c4c0c640ac07b89722271f866287b9047459        refs/heads/ALP-current
4993d1b0a96a0fa7fb0e87d3b1725bc775162283        refs/heads/ALP-current-RT
:~> python3
Python 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygit2
>>> pygit2.Repository("/srv/git/kernel-source.git")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/pygit2/repository.py", line 1498, in __init__
    path_backend = init_file_backend(path, flags)
_pygit2.GitError: Repository not found at /srv/git/kernel-source.git
>>>

Signed-off-by: Michal Suchanek <msuchanek@suse.de>